export const MODEL_PROVIDER_LOGOS: Record<
  string,
  {
    src: string;
    alt: string;
  }
> = {
  anthropic: { src: "/logos/Anthropic.svg", alt: "Anthropic" },
  alibaba: { src: "/logos/alibaba.png", alt: "Alibaba" },
  "amazon bedrock": { src: "/logos/Bedrock.svg", alt: "Amazon Bedrock" },
  ai21: { src: "/logos/ai21.png", alt: "AI21" },
  aionlabs: { src: "/logos/aionlabs.png", alt: "AionLabs" },
  atlascloud: { src: "/logos/atlascloud.png", alt: "AtlasCloud" },
  azure: { src: "/logos/Azure.svg", alt: "Azure" },
  baseten: { src: "/logos/baseten.svg", alt: "BaseTen" },
  cerebras: { src: "/logos/cerebras.png", alt: "Cerebras" },
  chutes: { src: "/logos/chutes.png", alt: "Chutes" },
  cohere: { src: "/logos/Cohere.png", alt: "Cohere" },
  cloudflare: { src: "/logos/cloudflare.png", alt: "Cloudflare" },
  crusoe: { src: "/logos/crusoe.png", alt: "Crusoe" },
  deepseek: { src: "/logos/deepseek.png", alt: "DeepSeek" },
  deepinfra: { src: "/logos/deepinfra.png", alt: "DeepInfra" },
  featherless: { src: "/logos/featherless.svg", alt: "Featherless" },
  fireworks: { src: "/logos/Fireworks.png", alt: "Fireworks" },
  friendli: { src: "/logos/friendli.png", alt: "Friendli" },
  gmicloud: { src: "/logos/gmicloud.png", alt: "GMICloud" },
  "google ai studio": { src: "/logos/GoogleAIStudio.png", alt: "Google AI Studio" },
  groq: { src: "/logos/groq.png", alt: "Groq" },
  "z.ai": { src: "/logos/zai.png", alt: "Z.AI" },
  xai: { src: "/logos/xai.png", alt: "xAI" },
  together: { src: "/logos/together.svg", alt: "Together" },
  perplexity: { src: "/logos/Perplexity.svg", alt: "Perplexity" },
  "weights and biases": { src: "/logos/wandb.png", alt: "Weights and Biases" },
  "google vertex": { src: "/logos/GoogleVertex.png", alt: "Google Vertex" },
  hyperbolic: { src: "/logos/hyperbolic.png", alt: "Hyperbolic" },
  meta: { src: "/logos/meta.png", alt: "Meta" },
  mistral: { src: "/logos/Mistral.png", alt: "Mistral" },
  inception: { src: "/logos/inception.png", alt: "Inception" },
  openai: { src: "/logos/openai.png", alt: "OpenAI" },
  nebius: { src: "/logos/nebius.png", alt: "Nebius" },
  novita: { src: "/logos/novita.jpeg", alt: "Novita" },
  inferencenet: { src: "/logos/inferencenet.png", alt: "InferenceNet" },
  nvidia: { src: "/logos/nvidia.png", alt: "NVIDIA" },
  infermatic: { src: "/logos/infermatic.png", alt: "Infermatic" },
  inflection: { src: "/logos/inflection.png", alt: "Inflection" },
  liquid: { src: "/logos/liquid.png", alt: "Liquid" },
  mancer: { src: "/logos/mancer.svg", alt: "Mancer" },
  minimax: { src: "/logos/minimax.png", alt: "MiniMax" },
  openinference: { src: "/logos/openinference.png", alt: "OpenInference" },
  parasail: { src: "/logos/parasail.png", alt: "Parasail" },
  phala: { src: "/logos/phala.png", alt: "Phala" },
  moonshotai: { src: "/logos/moonshot.png", alt: "Moonshot AI" },
  ncompass: { src: "/logos/ncompass.png", alt: "nCompass" },
  morph: { src: "/logos/morph.png", alt: "Morph" },
  nextbit: { src: "/logos/nextbit.png", alt: "NextBit" },
  relace: { src: "/logos/relace.png", alt: "Relace" },
  sambanova: { src: "/logos/sambanova.png", alt: "SambaNova" },
  siliconflow: { src: "/logos/siliconflow.png", alt: "SiliconFlow" },
  switchpoint: { src: "/logos/switchpoint.png", alt: "Switchpoint" },
  targon: { src: "/logos/targon.svg", alt: "Targon" },
  venice: { src: "/logos/venice.png", alt: "Venice" },
  qwen: { src: "/logos/Qwen.png", alt: "Qwen" },
  google: { src: "/logos/google.svg", alt: "Google" },
  "amazon nova": { src: "", alt: "Amazon Nova" },
  ambient: { src: "", alt: "Ambient" },
  "arcee ai": { src: "", alt: "Arcee AI" },
  avian: { src: "", alt: "Avian" },
  "black forest labs": { src: "", alt: "Black Forest Labs" },
  byteplus: { src: "", alt: "BytePlus" },
  cirrascale: { src: "", alt: "Cirrascale" },
  clarifai: { src: "", alt: "Clarifai" },
  inceptron: { src: "", alt: "Inceptron" },
  "io net": { src: "", alt: "Io Net" },
  mara: { src: "", alt: "Mara" },
  modelrun: { src: "", alt: "ModelRun" },
  modular: { src: "", alt: "Modular" },
  seed: { src: "", alt: "Seed" },
  sourceful: { src: "", alt: "Sourceful" },
  stealth: { src: "", alt: "Stealth" },
  stepfun: { src: "", alt: "StepFun" },
  streamlake: { src: "", alt: "StreamLake" },
  upstage: { src: "", alt: "Upstage" },
  xiaomi: { src: "", alt: "Xiaomi" },
};

export function getModelProviderLogo(provider?: string | null) {
  if (!provider) return null;
  const key = provider.toLowerCase().trim();
  const entry = MODEL_PROVIDER_LOGOS[key];
  if (!entry || !entry.src) return null;
  return entry;
}
