export const TOOL_PROVIDER_LOGOS: Record<
  string,
  {
    src: string;
    alt: string;
  }
> = {
  // Manual mapping for tools.
  // Keys should be lowercased + trimmed tool names.
  // AI/ML Frameworks & Libraries
  "hugging face transformers": { src: "/logos/favicons/HuggingFace.png", alt: "Hugging Face Transformers" },
  "pytorch": { src: "/logos/favicons/PyTorch.png", alt: "PyTorch" },
  "vllm": { src: "/logos/favicons/vLLM.png", alt: "vLLM" },
  "tensorflow": { src: "/logos/favicons/TensorFlow.png", alt: "TensorFlow" },
  "scikit-learn": { src: "/logos/favicons/scikitlearn.png", alt: "scikit-learn" },
  "flashattention": { src: "/logos/favicons/Github.png", alt: "FlashAttention" },
  "nccl": { src: "/logos/nvidia.png", alt: "NCCL" },
  "megatron-lm": { src: "/logos/nvidia.png", alt: "Megatron-LM" },
  "tensorrt-llm": { src: "/logos/nvidia.png", alt: "TensorRT-LLM" },
  "apache spark": { src: "/logos/favicons/ApacheSpark.png", alt: "Apache Spark" },
  "bitsandbytes": { src: "/logos/favicons/bitsandbytes.png", alt: "bitsandbytes" },
  "triton": { src: "/logos/openai.png", alt: "Triton" },
  "accelerate": { src: "/logos/favicons/HuggingFace.png", alt: "Accelerate" },
  "tensorrt": { src: "/logos/nvidia.png", alt: "TensorRT" },
  "cudnn": { src: "/logos/nvidia.png", alt: "cuDNN" },
  "fastapi": { src: "/logos/favicons/FastAPI.png", alt: "FastAPI" },
  "jax": { src: "/logos/favicons/JAX.png", alt: "JAX" },
  "mlflow": { src: "/logos/favicons/MLflow.png", alt: "MLflow" },
  "xgboost": { src: "/logos/favicons/XGBoost.png", alt: "XGBoost" },
  "apache kafka": { src: "/logos/favicons/ApacheKafka.png", alt: "Apache Kafka" },
  "text generation inference": { src: "/logos/favicons/HuggingFace.png", alt: "Text Generation Inference" },
  "xformers": { src: "/logos/meta.png", alt: "xFormers" },
  "apache airflow": { src: "/logos/favicons/ApacheAirflow.png", alt: "Apache Airflow" },
  "apache parquet": { src: "/logos/favicons/ApacheParquet.png", alt: "Apache Parquet" },
  "keras": { src: "/logos/favicons/Keras.png", alt: "Keras" },
  "lightgbm": { src: "/logos/favicons/LightGBM.png", alt: "LightGBM" },
  "delta lake": { src: "/logos/favicons/DeltaLake.png", alt: "Delta Lake" },
  "faiss": { src: "/logos/meta.png", alt: "FAISS" },
  "dvc": { src: "/logos/favicons/DVC.jpeg", alt: "DVC" },
  "catboost": { src: "/logos/favicons/CatBoost.png", alt: "CatBoost" },
  "deepspeed mii": { src: "/logos/favicons/DeepSpeedMII.png", alt: "DeepSpeed MII" },
  "shap": { src: "/logos/favicons/SHAP.png", alt: "SHAP" },
  "captum": { src: "/logos/favicons/Captum.png", alt: "Captum" },
  "tensorboard": { src: "/logos/favicons/TensorFlow.png", alt: "TensorBoard" },
  "fairscale": { src: "/logos/meta.png", alt: "FairScale" },
  "colossal-ai": { src: "/logos/favicons/Colossal.png", alt: "Colossal-AI" },
  "horovod": { src: "/logos/favicons/Uber.png", alt: "Horovod" },
  "great expectations": { src: "/logos/favicons/GreatExpectations.png", alt: "Great Expectations" },
  "gradio": { src: "/logos/favicons/Gradio.png", alt: "Gradio" },
  "torchserve": { src: "/logos/favicons/PyTorch.png", alt: "TorchServe" },
  "streamlit": { src: "/logos/favicons/Streamlit.png", alt: "Streamlit" },
  "bentoml": { src: "/logos/favicons/BentoML.png", alt: "BentoML" },
  "weights & biases": { src: "/logos/wandb.png", alt: "Weights & Biases" },
  "opencv": { src: "/logos/favicons/OpenCV.png", alt: "OpenCV" },
  "onnx runtime": { src: "/logos/favicons/Microsoft.png", alt: "ONNX Runtime" },
  "kserve": { src: "/logos/favicons/KServe.png", alt: "KServe" },
  "chroma": { src: "/logos/favicons/Chroma.png", alt: "Chroma" },
  "torchvision": { src: "/logos/favicons/PyTorch.png", alt: "TorchVision" },
  "flyte": { src: "/logos/favicons/Flyte.png", alt: "Flyte" },
  "milvus": { src: "/logos/favicons/Milvus.png", alt: "Milvus" },
  "evidently": { src: "/logos/favicons/Evidently.png", alt: "Evidently" },
  "weaviate": { src: "/logos/favicons/Weaviate.png", alt: "Weaviate" },
  "apache flink": { src: "/logos/favicons/ApacheFlink.png", alt: "Apache Flink" },
  "apache beam": { src: "/logos/favicons/ApacheBeam.png", alt: "Apache Beam" },
  "spacy": { src: "/logos/favicons/spaCy.png", alt: "spaCy" },
  "feast": { src: "/logos/favicons/Feast.png", alt: "Feast" },
  "llamaindex": { src: "/logos/favicons/LlamaIndex.png", alt: "LlamaIndex" },
  "haystack": { src: "/logos/favicons/Haystack.png", alt: "Haystack" },
  "ragflow": { src: "/logos/favicons/RAGFlow.png", alt: "RAGFlow" },
  "langchain": { src: "/logos/favicons/LangChain.png", alt: "LangChain" },
  "jupyterlab": { src: "/logos/favicons/Jupyter.png", alt: "JupyterLab" },
  "jupyter notebook": { src: "/logos/favicons/Jupyter.png", alt: "Jupyter Notebook" },
  "jupyterhub": { src: "/logos/favicons/Jupyter.png", alt: "JupyterHub" },
  "pinecone": { src: "/logos/favicons/Pinecone.png", alt: "Pinecone" },
  "qdrant": { src: "/logos/favicons/Qdrant.png", alt: "Qdrant" },
  "pgvector": { src: "/logos/favicons/Github.png", alt: "pgvector" },
  "elastic": { src: "/logos/favicons/Elastic.png", alt: "Elastic" },
  "opensearch": { src: "/logos/favicons/OpenSearch.png", alt: "OpenSearch" },
  "vespa": { src: "/logos/favicons/Vespa.png", alt: "Vespa" },
  "ray tune": { src: "/logos/favicons/RayTune.png", alt: "Ray Tune" },
  "dagster": { src: "/logos/favicons/Dagster.png", alt: "Dagster" },
  "dbt core": { src: "/logos/favicons/DBT.png", alt: "dbt Core" },
  "apache iceberg": { src: "/logos/favicons/ApacheIceberg.png", alt: "Apache Iceberg" },
  "apache hudi": { src: "/logos/favicons/ApacheHudi.png", alt: "Apache Hudi" },
  "sagemaker": { src: "/logos/favicons/AWS.png", alt: "SageMaker" },
  "google vertex ai": { src: "/logos/GoogleVertex.png", alt: "Google Vertex AI" },
  "azure machine learning": { src: "/logos/Azure.svg", alt: "Azure Machine Learning" },
  "databricks lakehouse": { src: "/logos/favicons/DataBricks.png", alt: "Databricks Lakehouse" },
  "cutlass": { src: "/logos/nvidia.png", alt: "CUTLASS" },
  "cublas": { src: "/logos/nvidia.png", alt: "cuBLAS" },
  "sentence transformers": { src: "/logos/favicons/HuggingFace.png", alt: "Sentence Transformers" },
  "nemo": { src: "/logos/nvidia.png", alt: "NeMo" },
  "clip": { src: "/logos/openai.png", alt: "CLIP" },
  "diffusers": { src: "/logos/favicons/HuggingFace.png", alt: "Diffusers" },
  "xla": { src: "/logos/favicons/XLA.png", alt: "XLA" },
  "iree": { src: "/logos/favicons/IREE.png", alt: "IREE" },
  "polars": { src: "/logos/favicons/Polars.png", alt: "Polars" },
  "llama.cpp": { src: "/logos/favicons/LlamaCPP.jpeg", alt: "llama.cpp" },
  "duckdb": { src: "/logos/favicons/DuckDB.png", alt: "DuckDB" },
  "clickhouse": { src: "/logos/favicons/ClickHouse.png", alt: "ClickHouse" },
  "guardrails": { src: "/logos/favicons/Guardrails.png", alt: "Guardrails" },
  "evaluate": { src: "/logos/favicons/HuggingFace.png", alt: "Evaluate" },
  "deepeval": { src: "/logos/favicons/DeepEval.png", alt: "DeepEval" },
  "flax": { src: "/logos/favicons/Google.png", alt: "Flax" },
  "text embeddings inference": { src: "/logos/favicons/HuggingFace.png", alt: "Text Embeddings Inference" },
  "deeplearning4j": { src: "/logos/favicons/DeepLearning4J.png", alt: "DeepLearning4J" },
  "paddlepaddle": { src: "/logos/favicons/PaddlePaddle.png", alt: "PaddlePaddle" },
  "oneflow": { src: "/logos/favicons/OneFlow.png", alt: "OneFlow" },
  "litellm": { src: "/logos/favicons/LiteLLM.png", alt: "LiteLLM" },
  "ollama": { src: "/logos/favicons/Ollama.png", alt: "Ollama" },
  "fastchat": { src: "/logos/favicons/FastChat.png", alt: "FastChat" },
  "petals": { src: "/logos/favicons/Petals.png", alt: "Petals" },
  "cohere": { src: "/logos/Cohere.png", alt: "Cohere" },
  "mistral ai": { src: "/logos/Mistral.png", alt: "Mistral AI" },
  "openrouter": { src: "/logos/favicons/OpenRouter.png", alt: "OpenRouter" },
  "anyscale endpoints": { src: "/logos/favicons/Anyscale.png", alt: "Anyscale Endpoints" },
  "prometheus": { src: "/logos/favicons/Prometheus.png", alt: "Prometheus" },
  "neural compressor": { src: "/logos/favicons/Intel.png", alt: "Neural Compressor" },
  "gptq": { src: "/logos/favicons/GPTQ.png", alt: "GPTQ" },
  "mosaic ai": { src: "/logos/favicons/DataBricks.png", alt: "Mosaic AI" },
  "lm studio": { src: "/logos/favicons/LMStudio.png", alt: "LM Studio" },
  "groq": { src: "/logos/groq.png", alt: "Groq" },
  "miopen": { src: "/logos/amd.png", alt: "MIOpen" },
  "dspy": { src: "/logos/favicons/DSPy.png", alt: "DSPy" },
  "exllama": { src: "/logos/favicons/EXLLAMA.jpeg", alt: "ExLlama" },
  "triton inference server": { src: "/logos/nvidia.png", alt: "Triton Inference Server" },
  "mlserver": { src: "/logos/favicons/AlibiDetect.png", alt: "MLServer" },
  "rapids": { src: "/logos/nvidia.png", alt: "RAPIDS" },
  "tensorflow serving": { src: "/logos/favicons/TensorFlow.png", alt: "TensorFlow Serving" },
  "cusparse": { src: "/logos/nvidia.png", alt: "cuSPARSE" },
  "dask": { src: "/logos/favicons/Dask.png", alt: "Dask" },
  "guidance": { src: "/logos/favicons/Guidance.png", alt: "Guidance" },
  "nemo guardrails": { src: "/logos/nvidia.png", alt: "NeMo Guardrails" },
  "prefect": { src: "/logos/favicons/Prefect.png", alt: "Prefect" },
  "baseten": { src: "/logos/baseten.svg", alt: "Baseten" },
  "replicate": { src: "/logos/favicons/Replicate.png", alt: "Replicate" },
  "kedro": { src: "/logos/favicons/Kedro.png", alt: "Kedro" },
  "seldon core": { src: "/logos/favicons/AlibiDetect.png", alt: "Seldon Core" },
  "outlines": { src: "/logos/favicons/Outlines.png", alt: "Outlines" },
  "spark rapids": { src: "/logos/nvidia.png", alt: "Spark RAPIDS" },
  "zenml": { src: "/logos/favicons/ZenML.png", alt: "ZenML" },
  "metaflow": { src: "/logos/favicons/Metaflow.png", alt: "Metaflow" },
  "garak": { src: "/logos/nvidia.png", alt: "Garak" },
  "luigi": { src: "/logos/favicons/Luigi.png", alt: "Luigi" },
  "argo workflows": { src: "/logos/favicons/ArgoCD.png", alt: "Argo Workflows" },
  "hamilton": { src: "/logos/favicons/Hamilton.png", alt: "Hamilton" },
  "ploomber": { src: "/logos/favicons/Ploomber.jpeg", alt: "Ploomber" },
  "modal": { src: "/logos/favicons/Modal.png", alt: "Modal" },
  "skypilot": { src: "/logos/favicons/SkyPilot.png", alt: "SkyPilot" },
  "lightning ai": { src: "/logos/favicons/LightningAI.png", alt: "Lightning AI" },
  "modin": { src: "/logos/favicons/Modin.png", alt: "Modin" },
  "pandas api on spark": { src: "/logos/favicons/ApacheSpark.png", alt: "Pandas API on Spark" },
  "gpflow": { src: "/logos/favicons/GPFlow.png", alt: "GPflow" },
  "gpytorch": { src: "/logos/favicons/Github.png", alt: "GPyTorch" },
  "pymc": { src: "/logos/favicons/PyMC.png", alt: "PyMC" },
  "dali": { src: "/logos/nvidia.png", alt: "DALI" },
  "stan": { src: "/logos/favicons/Stan.png", alt: "Stan" },
  "aim": { src: "/logos/favicons/AimStack.png", alt: "Aim" },
  "nvtabular": { src: "/logos/nvidia.png", alt: "NVTabular" },
  "statsmodels": { src: "/logos/favicons/Statsmodels.png", alt: "Statsmodels" },
  "pyod": { src: "/logos/favicons/ReadTheDocs.png", alt: "PyOD" },
  "featuretools": { src: "/logos/favicons/Featuretools.png", alt: "Featuretools" },
  "spark mllib": { src: "/logos/favicons/ApacheSpark.png", alt: "Spark MLlib" },
  "feature-engine": { src: "/logos/favicons/Featureengine.png", alt: "Feature-engine" },
  "sacred": { src: "/logos/favicons/Sacred.png", alt: "Sacred" },
  "category encoders": { src: "/logos/favicons/scikitlearn.png", alt: "Category Encoders" },
  "imbalanced-learn": { src: "/logos/favicons/scikitlearn.png", alt: "Imbalanced-learn" },
  "hugging face spaces": { src: "/logos/favicons/HuggingFace.png", alt: "Hugging Face Spaces" },
  "kubeflow": { src: "/logos/favicons/Kubeflow.png", alt: "Kubeflow" },
  "mlrun": { src: "/logos/favicons/MLRun.png", alt: "MLRun" },
  "polyaxon": { src: "/logos/favicons/Polyaxon.png", alt: "Polyaxon" },
  "clearml": { src: "/logos/favicons/ClearML.png", alt: "ClearML" },
  "comet": { src: "/logos/favicons/Comet.png", alt: "Comet" },
  "neptune": { src: "/logos/favicons/Neptune.png", alt: "Neptune" },
  "lakefs": { src: "/logos/favicons/lakeFS.png", alt: "lakeFS" },
  "pachyderm": { src: "/logos/favicons/Pachyderm.png", alt: "Pachyderm" },
  "dolt": { src: "/logos/favicons/Dolt.png", alt: "Dolt" },
  "alpa": { src: "/logos/favicons/Alpa.jpeg", alt: "Alpa" },
  "hnswlib": { src: "/logos/favicons/Github.png", alt: "HNSWlib" },
  "dagshub": { src: "/logos/favicons/DagsHub.png", alt: "DagsHub" },
  "apache pulsar": { src: "/logos/favicons/ApachePulsar.png", alt: "Apache Pulsar" },
  "annoy": { src: "/logos/favicons/Luigi.png", alt: "Annoy" },
  "scann": { src: "/logos/favicons/Google.png", alt: "ScaNN" },
  "marqo": { src: "/logos/favicons/Marqo.png", alt: "Marqo" },
  "trino": { src: "/logos/favicons/Trino.png", alt: "Trino" },
  "composer": { src: "/logos/favicons/Composer.png", alt: "Composer" },
  "dbt cloud": { src: "/logos/favicons/DBT.png", alt: "dbt Cloud" },
  "glue": { src: "/logos/favicons/AWS.png", alt: "Glue" },
  "redpanda": { src: "/logos/favicons/Redpanda.png", alt: "Redpanda" },
  "apache druid": { src: "/logos/favicons/ApacheDruid.png", alt: "Apache Druid" },
  "apache pinot": { src: "/logos/favicons/ApachePinot.png", alt: "Apache Pinot" },
  "prestodb": { src: "/logos/favicons/PrestoDB.png", alt: "PrestoDB" },
  "apache hive": { src: "/logos/favicons/ApacheHive.png", alt: "Apache Hive" },
  "hopsworks": { src: "/logos/favicons/Hopsworks.png", alt: "Hopsworks" },
  "bigquery": { src: "/logos/GoogleVertex.png", alt: "BigQuery" },
  "snowflake": { src: "/logos/favicons/Snowflake.png", alt: "Snowflake" },
  "tecton": { src: "/logos/favicons/DataBricks.png", alt: "Tecton" },
  "segment anything": { src: "/logos/meta.png", alt: "Segment Anything" },
  "featureform": { src: "/logos/favicons/Featureform.png", alt: "Featureform" },
  "detectron2": { src: "/logos/meta.png", alt: "Detectron2" },
  "redis feature store": { src: "/logos/favicons/RedisFeatureStore.png", alt: "Redis Feature Store" },
  "mmdetection": { src: "/logos/favicons/MMDetection.png", alt: "MMDetection" },
  "groundingdino": { src: "/logos/favicons/GroundingDino.jpg", alt: "GroundingDINO" },
  "albumentations": { src: "/logos/favicons/Albumentations.png", alt: "Albumentations" },
  "langflow": { src: "/logos/favicons/Langflow.png", alt: "Langflow" },
  "autogen": { src: "/logos/favicons/Microsoft.png", alt: "AutoGen" },
  "crewai": { src: "/logos/favicons/CrewAI.png", alt: "CrewAI" },
  "semantic kernel": { src: "/logos/favicons/Microsoft.png", alt: "Semantic Kernel" },
  "fairseq": { src: "/logos/meta.png", alt: "Fairseq" },
  "fasttext": { src: "/logos/favicons/fastText.png", alt: "fastText" },
  "gensim": { src: "/logos/favicons/Gensim.png", alt: "Gensim" },
  "opennmt": { src: "/logos/favicons/OpenNMT.png", alt: "OpenNMT" },
  "detoxify": { src: "/logos/favicons/Detoxify.png", alt: "Detoxify" },
  "tao toolkit": { src: "/logos/nvidia.png", alt: "TAO Toolkit" },
  "deepstream sdk": { src: "/logos/nvidia.png", alt: "DeepStream SDK" },
  "autogluon": { src: "/logos/favicons/AutoGluon.png", alt: "AutoGluon" },
  "pandera": { src: "/logos/favicons/Pandera.png", alt: "Pandera" },
  "lightautoml": { src: "/logos/favicons/LightAutoML.png", alt: "LightAutoML" },
  "cleanlab": { src: "/logos/favicons/Cleanlab.png", alt: "Cleanlab" },
  "deepchecks": { src: "/logos/favicons/Deepchecks.png", alt: "Deepchecks" },
  "deequ": { src: "/logos/favicons/AWS.png", alt: "Deequ" },
  "trulens": { src: "/logos/favicons/TruLens.png", alt: "TruLens" },
  "giskard": { src: "/logos/favicons/Giskard.png", alt: "Giskard" },
  "openai evals": { src: "/logos/openai.png", alt: "OpenAI Evals" },
  "whylogs": { src: "/logos/favicons/WhyLogs.png", alt: "Whylogs" },
  "ax": { src: "/logos/favicons/Ax.png", alt: "Ax" },
  "botorch": { src: "/logos/favicons/BoTorch.png", alt: "BoTorch" },
  "hyperopt": { src: "/logos/favicons/Hyperopt.png", alt: "Hyperopt" },
  "nevergrad": { src: "/logos/meta.png", alt: "Nevergrad" },
  "langfuse": { src: "/logos/favicons/Langfuse.png", alt: "Langfuse" },
  "nannyml": { src: "/logos/favicons/NannyML.png", alt: "NannyML" },
  "h2o-3": { src: "/logos/favicons/H2O3.png", alt: "H2O-3" },
  "flaml": { src: "/logos/favicons/FLAML.png", alt: "FLAML" },
  "pycaret": { src: "/logos/favicons/PyCaret.png", alt: "PyCaret" },
  "tpot": { src: "/logos/favicons/TPOT.png", alt: "TPOT" },
  "auto-sklearn": { src: "/logos/favicons/AutoSklearn.png", alt: "auto-sklearn" },
  "autokeras": { src: "/logos/favicons/AutoKeras.png", alt: "AutoKeras" },
  "ludwig": { src: "/logos/favicons/Ludwig.png", alt: "Ludwig" },
  "mindsdb": { src: "/logos/favicons/MindsDB.png", alt: "MindsDB" },
  "phoenix": { src: "/logos/favicons/Arize.png", alt: "Phoenix" },
  "langsmith": { src: "/logos/favicons/LangChain.png", alt: "LangSmith" },
  "alibi detect": { src: "/logos/favicons/AlibiDetect.png", alt: "Alibi Detect" },
  "datarobot": { src: "/logos/favicons/DataRobot.png", alt: "DataRobot" },
  "promptlayer": { src: "/logos/favicons/PromptLayer.png", alt: "PromptLayer" },
  "arize": { src: "/logos/favicons/Arize.png", alt: "Arize" },
  "fiddler": { src: "/logos/favicons/Fiddler.png", alt: "Fiddler" },
  "superwise": { src: "/logos/favicons/Superwise.png", alt: "Superwise" },
  "lime": { src: "/logos/favicons/Github.png", alt: "LIME" },
  "interpretml": { src: "/logos/favicons/InterpretML.png", alt: "InterpretML" },
  "eli5": { src: "/logos/favicons/ELI5.png", alt: "ELI5" },
  "dice": { src: "/logos/favicons/InterpretML.png", alt: "DiCE" },
  "omnixai": { src: "/logos/favicons/OmniXAI.png", alt: "OmniXAI" },
  "what-if tool": { src: "/logos/favicons/WhatIfTool.png", alt: "What-If Tool" },
  "aix360": { src: "/logos/favicons/AI360X.png", alt: "AIX360" },
  "label studio": { src: "/logos/favicons/LabelStudio.png", alt: "Label Studio" },
  "cvat": { src: "/logos/favicons/CVAT.png", alt: "CVAT" },
  "airbyte": { src: "/logos/favicons/Airbyte.png", alt: "Airbyte" },
  "monte carlo": { src: "/logos/favicons/MonteCarlo.png", alt: "Monte Carlo" },
  "openclip": { src: "/logos/favicons/Github.png", alt: "OpenCLIP" },
  "lavis": { src: "/logos/favicons/OmniXAI.png", alt: "LAVIS" },
  "alibi": { src: "/logos/favicons/AlibiDetect.png", alt: "Alibi" },
  "doccano": { src: "/logos/favicons/Doccano.png", alt: "Doccano" },
  "openvino": { src: "/logos/favicons/OpenVINO.png", alt: "OpenVINO" },
  "apache tvm": { src: "/logos/favicons/ApacheTVM.png", alt: "Apache TVM" },
  "debezium": { src: "/logos/favicons/Debezium.png", alt: "Debezium" },
  "meltano": { src: "/logos/favicons/Meltano.png", alt: "Meltano" },
  "singer": { src: "/logos/favicons/Singer.png", alt: "Singer" },
  "apache arrow flight": { src: "/logos/favicons/ApacheArrowFlight.png", alt: "Apache Arrow Flight" },
  "alluxio": { src: "/logos/favicons/Alluxio.png", alt: "Alluxio" },
  "kafka connect": { src: "/logos/favicons/ApacheKafka.png", alt: "Kafka Connect" },
  "glow": { src: "/logos/favicons/PyTorch.png", alt: "Glow" },
  "mlir": { src: "/logos/favicons/MLIR.png", alt: "MLIR" },
  "rebuff": { src: "/logos/favicons/Rebuff.png", alt: "Rebuff" },
  "roboflow": { src: "/logos/favicons/Roboflow.png", alt: "Roboflow" },
  "scale ai": { src: "/logos/favicons/ScaleAI.png", alt: "Scale AI" },
  "labelbox": { src: "/logos/favicons/Labelbox.png", alt: "Labelbox" },
  "superannotate": { src: "/logos/favicons/SuperAnnotate.jpg", alt: "SuperAnnotate" },
  "supervisely": { src: "/logos/favicons/Supervisely.png", alt: "Supervisely" },
  "v7": { src: "/logos/favicons/V7.png", alt: "V7" },
  "dataloop": { src: "/logos/favicons/Dataloop.png", alt: "Dataloop" },
  "datasaur": { src: "/logos/favicons/Datasaur.png", alt: "Datasaur" },
  "prodigy": { src: "/logos/favicons/Prodigy.png", alt: "Prodigy" },
  "snorkel flow": { src: "/logos/favicons/SnorkelFlow.png", alt: "Snorkel Flow" },
  "grafana": { src: "/logos/favicons/Grafana.png", alt: "Grafana" },
  "optuna dashboard": { src: "/logos/favicons/OptunaDashboard.png", alt: "Optuna Dashboard" },
  "metabase": { src: "/logos/favicons/Metabase.png", alt: "Metabase" },
  "dash": { src: "/logos/favicons/Dash.png", alt: "Dash" },
  "netron": { src: "/logos/favicons/Netron.png", alt: "Netron" },
  "apache superset": { src: "/logos/favicons/ApacheSuperset.png", alt: "Superset" },
  "lakera": { src: "/logos/favicons/Lakera.png", alt: "Lakera" },
  "grype": { src: "/logos/favicons/Grype.jpeg", alt: "Grype" },
  "grafeas": { src: "/logos/favicons/Grafeas.png", alt: "Grafeas" },
  "kritis": { src: "/logos/favicons/Grafeas.png", alt: "Kritis" },
  "cugraph": { src: "/logos/nvidia.png", alt: "cuGraph" },
  "protect ai": { src: "/logos/favicons/ProtectAI.png", alt: "Protect AI" },
  "whisper": { src: "/logos/openai.png", alt: "Whisper" },
  "dgl": { src: "/logos/favicons/DGL.png", alt: "DGL" },
  "pytorch geometric": { src: "/logos/favicons/PyTorchGeometric.png", alt: "PyTorch Geometric" },
  "graphstorm": { src: "/logos/favicons/AWS.png", alt: "GraphStorm" },
  "spektral": { src: "/logos/favicons/Spektral.png", alt: "Spektral" },
  "hugectr": { src: "/logos/nvidia.png", alt: "HugeCTR" },
  "merlin systems": { src: "/logos/nvidia.png", alt: "Merlin Systems" },
  "recbole": { src: "/logos/favicons/RecBole.png", alt: "RecBole" },
  "lenskit": { src: "/logos/favicons/LensKit.png", alt: "LensKit" },
  "lightfm": { src: "/logos/favicons/LightFM.png", alt: "LightFM" },
  "spotlight": { src: "/logos/favicons/Spotlight.jpeg", alt: "Spotlight" },
  "surprise": { src: "/logos/favicons/Github.png", alt: "Surprise" },
  "implicit": { src: "/logos/favicons/Github.png", alt: "implicit" },
  "xlearn": { src: "/logos/favicons/Github.png", alt: "XLearn" },
  "prophet": { src: "/logos/favicons/Prophet.png", alt: "Prophet" },
  "chronos": { src: "/logos/favicons/AmazonScience.png", alt: "Chronos" },
  "darts": { src: "/logos/favicons/Darts.png", alt: "Darts" },
  "merlion": { src: "/logos/favicons/OmniXAI.png", alt: "Merlion" },
  "tsfresh": { src: "/logos/favicons/TSFresh.jpeg", alt: "TSFresh" },
  "kats": { src: "/logos/meta.png", alt: "Kats" },
  "greykite": { src: "/logos/favicons/LinkedIN.png", alt: "Greykite" },
  "orbit": { src: "/logos/favicons/Uber.png", alt: "Orbit" },
  "ai fairness 360": { src: "/logos/favicons/AI360X.png", alt: "AI Fairness 360" },
  "fairlearn": { src: "/logos/favicons/Fairlearn.png", alt: "Fairlearn" },
  "fat forensics": { src: "/logos/favicons/FATForensics.png", alt: "FAT Forensics" },
  "themis-ml": { src: "/logos/favicons/Github.png", alt: "Themis-ML" },
  "espnet": { src: "/logos/favicons/ESPnet.png", alt: "ESPnet" },
  "kaldi": { src: "/logos/favicons/Kaldi.png", alt: "Kaldi" },
  "torchaudio": { src: "/logos/favicons/TorchAudio.png", alt: "TorchAudio" },
  "librosa": { src: "/logos/favicons/Librosa.png", alt: "Librosa" },
  "gymnasium": { src: "/logos/favicons/Gymnasium.png", alt: "Gymnasium" },
  "stable baselines3": { src: "/logos/favicons/ReadTheDocs.png", alt: "Stable Baselines3" },
  "responsible ai dashboard": { src: "/logos/favicons/Microsoft.png", alt: "Responsible AI Dashboard" },
  "model card toolkit": { src: "/logos/favicons/TensorFlow.png", alt: "Model Card Toolkit" },
  "ai risk atlas": { src: "/logos/favicons/IBM.jpeg", alt: "AI Risk Atlas" },
  "gpu operator": { src: "/logos/nvidia.png", alt: "GPU Operator" },
  "rocm": { src: "/logos/amd.png", alt: "ROCm" },
  "apptainer": { src: "/logos/favicons/Apptainer.png", alt: "Apptainer" },
  "singularity": { src: "/logos/favicons/Singularity.png", alt: "Singularity" },
  "arthur": { src: "/logos/favicons/Arthur.png", alt: "Arthur" },
  "credo ai": { src: "/logos/favicons/CredoAI.png", alt: "Credo AI" },
  "holistic ai": { src: "/logos/favicons/HolisticAI.png", alt: "Holistic AI" },
  "monitaur": { src: "/logos/favicons/Monitaur.png", alt: "Monitaur" },
  "cerebras": { src: "/logos/cerebras.png", alt: "Cerebras" },
  "kai scheduler": { src: "/logos/nvidia.png", alt: "KAI Scheduler" },
  "slurm": { src: "/logos/favicons/Slurm.png", alt: "Slurm" },
  "run:ai": { src: "/logos/nvidia.png", alt: "Run:AI" },
  "nvidia base command manager": { src: "/logos/nvidia.png", alt: "NVIDIA Base Command Manager" },
  "gazebo": { src: "/logos/favicons/Gazebo.png", alt: "Gazebo" },
  "mujoco": { src: "/logos/favicons/MuJoCo.png", alt: "MuJoCo" },
  "pybullet": { src: "/logos/favicons/PyBullet.png", alt: "PyBullet" },
  "carla": { src: "/logos/favicons/CARLA.png", alt: "CARLA" },
  "habitat-sim": { src: "/logos/favicons/HabitatSim.png", alt: "Habitat-Sim" },
  "habitat-lab": { src: "/logos/favicons/HabitatLab.png", alt: "Habitat-Lab" },
  "jetpack": { src: "/logos/nvidia.png", alt: "JetPack" },
  "fleet command": { src: "/logos/nvidia.png", alt: "Fleet Command" },
  "isaac ros": { src: "/logos/nvidia.png", alt: "Isaac ROS" },
  "moveit": { src: "/logos/favicons/MoveIt.png", alt: "MoveIt" },
  "rosbag2": { src: "/logos/favicons/Github.png", alt: "rosbag2" },
  "isaac sim": { src: "/logos/nvidia.png", alt: "Isaac Sim" },
  "unity perception": { src: "/logos/favicons/Unity.png", alt: "Unity Perception" },
  "omniverse replicator": { src: "/logos/nvidia.png", alt: "Omniverse Replicator" },
  "mostly ai": { src: "/logos/favicons/MostlyAI.png", alt: "Mostly AI" },
  "tensorflow federated": { src: "/logos/favicons/TensorFlow.png", alt: "TensorFlow Federated" },
  "flower": { src: "/logos/favicons/Flower.png", alt: "Flower" },
  "fedml": { src: "/logos/favicons/FedML.png", alt: "FedML" },
  "openfl": { src: "/logos/favicons/OpenFL.png", alt: "OpenFL" },
  "synthesis ai": { src: "/logos/favicons/SynthesisAI.png", alt: "Synthesis AI" },
  "unreal engine": { src: "/logos/favicons/UnrealEngine.png", alt: "Unreal Engine" },
  "pysyft": { src: "/logos/favicons/PySyft.png", alt: "PySyft" },
  "opacus": { src: "/logos/favicons/PyTorch.png", alt: "Opacus" },
  "tensorflow privacy": { src: "/logos/favicons/TensorFlow.png", alt: "TensorFlow Privacy" },
  "tf encrypted": { src: "/logos/favicons/TFEncrypted.png", alt: "TF Encrypted" },
  "google differential privacy": { src: "/logos/favicons/Google.png", alt: "Google Differential Privacy" },
  "ibm diffprivlib": { src: "/logos/favicons/IBM.jpeg", alt: "IBM Diffprivlib" },
  "opendp": { src: "/logos/favicons/OpenDP.png", alt: "OpenDP" },
  "smartnoise sdk": { src: "/logos/favicons/OpenDP.png", alt: "SmartNoise SDK" },
  "secretflow": { src: "/logos/favicons/SecretFlow.png", alt: "SecretFlow" },
  "clara fl": { src: "/logos/nvidia.png", alt: "Clara FL" },
  "apache cassandra": { src: "/logos/favicons/ApacheCassandra.png", alt: "Apache Cassandra" },
  "rocksdb": { src: "/logos/meta.png", alt: "RocksDB" },
  "tidb": { src: "/logos/favicons/TiDB.png", alt: "TiDB" },
  "neo4j": { src: "/logos/favicons/Neo4j.png", alt: "Neo4j" },
  "google confidential vms": { src: "/logos/GoogleVertex.png", alt: "Google Confidential VMs" },
  "nvidia confidential computing": { src: "/logos/nvidia.png", alt: "NVIDIA Confidential Computing" },
  "nitro enclaves": { src: "/logos/favicons/AWS.png", alt: "Nitro Enclaves" },
  "amundsen": { src: "/logos/favicons/Amundsen.png", alt: "Amundsen" },
  "datahub": { src: "/logos/favicons/LinkedIN.png", alt: "DataHub" },
  "apache atlas": { src: "/logos/favicons/ApacheAtlas.png", alt: "Apache Atlas" },
  "openmetadata": { src: "/logos/favicons/OpenMetadata.png", alt: "OpenMetadata" },
  "metacat": { src: "/logos/favicons/Metacat.png", alt: "Metacat" },
  "scylladb": { src: "/logos/favicons/ScyllaDB.png", alt: "ScyllaDB" },
  "ml metadata": { src: "/logos/favicons/Google.png", alt: "ML Metadata" },
  "modeldb": { src: "/logos/favicons/Github.png", alt: "ModelDB" },
  "hydra": { src: "/logos/meta.png", alt: "Hydra" },
  "omegaconf": { src: "/logos/favicons/OmegaConf.png", alt: "OmegaConf" },
  "vertex ai model registry": { src: "/logos/GoogleVertex.png", alt: "Vertex AI Model Registry" },
  "cml": { src: "/logos/favicons/CML.png", alt: "CML" },
  "argo cd": { src: "/logos/favicons/ArgoCD.png", alt: "Argo CD" },
  "pytorch profiler": { src: "/logos/favicons/PyTorch.png", alt: "PyTorch Profiler" },
  "scalene": { src: "/logos/favicons/Plasma.png", alt: "Scalene" },
  "py-spy": { src: "/logos/favicons/Github.png", alt: "py-spy" },
  "line profiler": { src: "/logos/favicons/lineprofiler.png", alt: "Line Profiler" },
  "memory profiler": { src: "/logos/favicons/Github.png", alt: "Memory Profiler" },
  "snakeviz": { src: "/logos/favicons/SnakeViz.png", alt: "SnakeViz" },
  "mlcommons": { src: "/logos/favicons/MLCommons.png", alt: "MLCommons" },
  "nsight compute": { src: "/logos/nvidia.png", alt: "Nsight Compute" },
  "nsight systems": { src: "/logos/nvidia.png", alt: "Nsight Systems" },
};

export function getToolProviderLogo(provider?: string | null) {
  if (!provider) return null;
  const key = provider.toLowerCase().trim();

  // Strictly use the map, no fallback heuristics
  return TOOL_PROVIDER_LOGOS[key] ?? null;
}
