interface ProviderParameter {
  name: string;
  parameter: string;
}

export const providerParameters: ProviderParameter[] = [
  { name: "AI21", parameter: "AI21" },
  { name: "AionLabs", parameter: "AionLabs" },
  { name: "Alibaba Cloud Int.", parameter: "Alibaba" },
  { name: "Amazon Bedrock", parameter: "Amazon%20Bedrock" },
  { name: "Anthropic", parameter: "Anthropic" },
  { name: "AtlasCloud", parameter: "AtlasCloud" },
  { name: "Atoma", parameter: "Atoma" },
  { name: "Avian.io", parameter: "Avian" },
  { name: "Azure", parameter: "Azure" },
  { name: "Baseten", parameter: "BaseTen" },
  { name: "Cerebras", parameter: "Cerebras" },
  { name: "Chutes", parameter: "Chutes" },
  { name: "Cloudflare", parameter: "Cloudflare" },
  { name: "Cohere", parameter: "Cohere" },
  { name: "CrofAI", parameter: "CrofAI" },
  { name: "Crusoe", parameter: "Crusoe" },
  { name: "DeepInfra", parameter: "DeepInfra" },
  { name: "DeepSeek", parameter: "DeepSeek" },
  { name: "Enfer", parameter: "Enfer" },
  { name: "Featherless", parameter: "Featherless" },
  { name: "Fireworks", parameter: "Fireworks" },
  { name: "Friendli", parameter: "Friendli" },
  { name: "GMICloud", parameter: "GMICloud" },
  { name: "Google AI Studio", parameter: "Google%20AI%20Studio" },
  { name: "Google Vertex", parameter: "Google" },
  { name: "Groq", parameter: "Groq" },
  { name: "Hyperbolic", parameter: "Hyperbolic" },
  { name: "Inception", parameter: "Inception" },
  { name: "inference.net", parameter: "InferenceNet" },
  { name: "Infermatic", parameter: "Infermatic" },
  { name: "Inflection", parameter: "Inflection" },
  { name: "kluster.ai", parameter: "Kluster" },
  { name: "Lambda", parameter: "Lambda" },
  { name: "Liquid", parameter: "Liquid" },
  { name: "Mancer (private)", parameter: "Mancer%202" },
  { name: "Meta", parameter: "Meta" },
  { name: "Minimax", parameter: "Minimax" },
  { name: "Mistral", parameter: "Mistral" },
  { name: "Moonshot AI", parameter: "Moonshot%20AI" },
  { name: "Morph", parameter: "Morph" },
  { name: "nCompass", parameter: "NCompass" },
  { name: "Nebius", parameter: "Nebius" },
  { name: "NextBit", parameter: "NextBit" },
  { name: "Nineteen", parameter: "Nineteen" },
  { name: "Novita", parameter: "Novita" },
  { name: "NVIDIA", parameter: "Nvidia" },
  { name: "OpenAI", parameter: "OpenAI" },
  { name: "OpenInference", parameter: "OpenInference" },
  { name: "Parasail", parameter: "Parasail" },
  { name: "Perplexity", parameter: "Perplexity" },
  { name: "Phala", parameter: "Phala" },
  { name: "Relace", parameter: "Relace" },
  { name: "SambaNova", parameter: "SambaNova" },
  { name: "SiliconFlow", parameter: "SiliconFlow" },
  { name: "Stealth", parameter: "Stealth" },
  { name: "Switchpoint", parameter: "Switchpoint" },
  { name: "Targon", parameter: "Targon" },
  { name: "Together", parameter: "Together" },
  { name: "Ubicloud", parameter: "Ubicloud" },
  { name: "Venice", parameter: "Venice" },
  { name: "Weights & Biases", parameter: "WandB" },
  { name: "xAI", parameter: "xAI" },
  { name: "Z.AI", parameter: "Z.AI" },
];
